name: egitimciler
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  google_fonts: ^6.2.1
  shared_preferences: ^2.1.1
  supabase_flutter: ^2.10.0
  sign_in_with_apple: ^6.0.0
  google_sign_in: ^6.1.0
   # Güncel sürüm, Android ve iOS uyumlu

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/png/splash/splash.png
    - assets/png/onboarding/onboarding1.png
    - assets/png/onboarding/onboarding2.png
    - assets/png/onboarding/onboarding3.png
